### PR TITLE
Repository Section

### LINKED ISSUE #13: [Feature Request]: Repo Section on the home page of the website.
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

There a need of a Repositories section on the home page of the webiste, which lists all the repos at the single place with the following details:
- Repo Name
- Description
- Stars
- Direct links to the repo.
- etc....

### Proposed Solution

Prepare a UI based on the idea of above reference and also maintaing the color scheme and UI of the [Open-Certs](https://open-certs.dev).

### Alternatives Considered

NA

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by shelabh**
# Description:

I have added the repository section on the home page.

The preview:-
Screenshot 2022-03-17 at 3 09 07 PM

Kindly review the changes.

Fixes #13

### CODE REVIEW

**Comment by Adi-11** [comment]
Screenshot from 2022-03-18 20-34-31

@shelabh  please look at the margin below the repo section its showing white space.

**Comment by shelabh** [comment]
@Adi-11 I'll fix that right away

**Comment by Adi-11** [comment]
@shelabh make sure to get the pull of the latest changes then start on refactoring.

**Comment by shelabh** [comment]
@Adi-11 I am creating the pull request of recent changes right away.

**Comment by Adi-11** [comment]
@shelabh and also resolve the conflict.

**Pull request closed without merging**
